version: 0.1

projects:
  - path: "./v0.02/terraform/dev/web-application/main/"
    usage_file: "./v0.02/terraform/dev/infracost/infracost-usage.yml"
    terraform_plan_flags: -var-file=dev.tfvars
    